### ISSUE TITLE
Is it possible, to have more than one blogroll?

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#108]
Hi.

Situation: I have one site, but different blogs in one site, to separate themes from another.

I have played around with adjustments in the demo data, see if I can operate in a site multiple blogs side by side. However, functions for the tag filter, etc. collide. Is this solvable at a reasonable effort?

I have an alternative idea, so that's not a knock-out criteria, it interests me basically.

Regards,
NoSi

**Comment by markseu** [comment]
Yes, you can have multiple blogs on your website. Here is an example:

- [Download the Yellow demo](https://github.com/datenstrom/yellow-demo) and duplicate the folder `content/2-blog`
- Rename your new folder `content/2-articles`
- Edit your new `page.txt` and change `Title: Articles` at the top
- Edit your individual articles and add `Template: blog` to the top
- Now you should have two different blogs

How does it work? The template setting will tell plugins what to do. If there is no template setting in a page, then Yellow will check if there is a template with the name of the current folder. This is what happens when you have a folder called `2-blog`, the blog template is automatically used. When you rename the blog folder to `2-articles`, then you need to tell manually which pages are blog articles. Please add the template setting only to single blog pages, don’t add it to a page that already has one. 

Let me know if this works for you.

**Comment by markseu** [comment]
Here's an updated example for Yellow 0.6.6:

1. [Download and unzip Yellow](https://github.com/datenstrom/yellow/archive/master.zip), select 'Blog' during installation
2. Duplicate the folder `content/2-blog` and name it `content/3-articles`
3. Edit file `content/3-articles/page.txt` and change `Title: Articles` at the top
4. Edit remaining files in your articles folder and add `Template: blog` to the top
5. Create a new file for the webinterface, see example below
6. That's it, you should have two different blogs now

Example file `system/config/page-new-articles.txt`:

```
---
Title: Page
Published: @datetime
Author: @username
Template: blog
Tag: Example
---
This is a new article page.
```

How does it work? The template setting will tell Yellow what to do. If there is no template setting in a page, then Yellow will check if there is a template with the name of the current folder. This is what happens when you have a folder called `2-blog`, the blog template is automatically used. When you rename the blog folder to `3-articles`, then you need to tell manually which pages are blog pages.

What's the alternative? Create a normal blog and a custom navigation snippet to show tags. For example`Tag: article` and `Tag:web` will give you location `/blog/tag:article/` and `/blog/tag:web/`. https://developers.datenstrom.se/help/yellow-templates#custom-navigation

**Comment by BsNoSi** [comment]
Hi Mark — this looks very interesting. I have a project in the near future I will try this technique. The usage of Yellow I decided weeks ago…  .;)

**Comment by markseu** [comment]
Here's an update for Yellow 0.7.1: Now it's just a copy-paste action, see steps 2 and 3 above. 

Let's say you want to write a news blog and a video blog. You can put your pages into separate folders and edit them independently. Alternatively you can put everything into one folder, then use `Tag: News` and `Tag: Video` to categorise similar pages.
