### ISSUE TITLE
Changing the Blog Default Directory

### ISSUE THREAD

**Issue by bstp** [datenstrom/yellow#144]
Hello,

I'll be using the Blog plugin for my portfolio of past projects.

This means the default URL "blog" doesn't fit that purpose.

I've edited this line in blog.php:

> $this->yellow->config->setDefault("blogLocation", "/portfolio/");

The name "portfolio" replaces "blog."

Everything seems to work so far with everything else installed as prescribed in the docs.

Would you suggest another way to proceed?

In any case, I thought it would be nice to let people know.

**Comment by bstp** [comment]
Dang,

Seems I broke the Internet again by trying to eliminate any "blog" from appearing in the URL.

The entries can't be read anymore. The sidebar can, however. Strange.

I'll report when I find why.

**Comment by bstp** [comment]
OK, I found what's going on:

- The entries can't be found back when I rename the blog repositories something else than "N-blog" where N is a number.

- What I thought was caused by renaming the blogLocation in blog.php has been caused by giving another value to the title field in the relevant page.txt

So back to square one.

**Comment by markseu** [comment]
Yes, you can use the [blog plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/blog) at a different location. Here is an example:

1. Rename your blog folder to `content/2-portfolio` and open it
2. Edit your blog pages and add `Template: blog` to the top of all pages, if there isn't one already
3. Edit your `system/config/page-new-blog.txt` and add `Template: blog` to the top of the page

How does it work? The [template](https://github.com/datenstrom/yellow/wiki/Yellow-customisation#templates) setting defines the functionality of your website. If there is none, then Yellow will check if there is a template with the name of the current folder. This is what happens when you have a folder called `2-blog`, the blog template is automatically used. When you rename the blog folder to `2-portfolio`, then you need to tell manually which pages are "blog pages".

Hope this helps. :smile:

**Comment by bstp** [comment]
It finally works. Thanks!

I had to work a bit, however. Here's what I seem to have needed in my `/portfolio/` directory:

- a `page.txt` file with the proper title and the line `Template: blogpages` 
- a `page-new-blog.txt` with a `Template: blog`
- blog posts files with the line `Template: blog`

Is this correct?

**Comment by markseu** [comment]
Yes, that's correct.

**Comment by markseu** [comment]
Just ask if there are more questions. :smile:
