### ISSUE TITLE
How Yellow CMS upgrade

### ISSUE THREAD

**Issue by AlexL777** [datenstrom/yellow#176]
Hello Developers,

I wonder just how to Yellow CMS upgrade. I find nowhere a guide and have the new version uploaded to the server. The user I immediately deleted.

Should we just upload yellow.php? Do I understand this in the right manner?

**Comment by schulle4u** [comment]
Normally you just need to overwrite everything, except for the `system/config` folder and other files you might have modiefied. However, since most users will modify themes and snippets, upgrading an installation have to be done with caution sometimes. Also the configuration values have to be re-applied if there are structural changes. Most important files are in `system/plugins` and it should be no problem to overwrite them. 

I think there should be a short release note for every major update for those who don't work with github, describing which files have been changed. Since Yellow's core only consists of a few files, this shouldn't be to complicated.

**Comment by AlexL777** [comment]
Thank you for your quick response and now I can see my family tell readers how to upgrade. I've re-created the user with SSH and that was no problem. One can communicate outside.

**Comment by markseu** [comment]
A tip for website administrators, you can check at the [command line](https://github.com/datenstrom/yellow-plugins/tree/master/commandline) if updates are available. You need two things. A web server with shell access and some experience to work with the command line interface. Log in via ssh, go to your Yellow installation and type `php yellow.php version`. Hope this helps. 😄

**Comment by markseu** [comment]
See also #187
