### ISSUE TITLE
Plugin dependencies / interaction

### ISSUE THREAD

**Issue by redtide** [datenstrom/yellow#191]
My bootstrap plugin uses external js/css sources: bootstrap and jquery.
Now I would like to keep jquery in a separated plugin (that was done already by someone else) to avoid to add duplicated style/script references on the resulting page.
The problem is that it seems there is not a plugin loading sequence order, so jquery gets loaded after bootstrap one and so my plugin will not work properly.

**Comment by markseu** [comment]
Plugins are loaded in alphabetical order. You could change the name of your plugin. As an alternative, your plugin could add all necessary headers including jQuery. Yellow should automatically remove duplicated styles and scripts. For example see https://github.com/nogginfuel/yellow-plugin-fotorama/blob/master/fotorama.php

What do you think, would this work?

**Comment by redtide** [comment]
I just needed to know how the load order was handled, so it's fine to me.
I asked about it also because I was going to make a MD editor replacement plugin that uses font awesome (SimpleMDE) so I was wondering what to do in that case too.
I'll see what can I do and thank you also for the alternative suggestion.

**Comment by schulle4u** [comment]
I'll follow up on this issue, since I have a similar problem now. 

Currently I'm working on a small plugin which includes a javascript file and some JSON array in the footer. Problem is that the JSON code needs to be included before the actual javascript file. Whatever I do, the JSON code always is shown after the javascript file. I tried inserting some HTML comments to force sorting of output variables and so on, still no luck. 

https://github.com/schulle4u/yellow-plugin-skipto/blob/master/skipto.php

Any idea how to solve this? 

Steffen

**Comment by markseu** [comment]
I'll have a look at your code tomorrow.

Btw, in the latest core you can register plugins with a priority. For example when a plugin needs to be loaded before (set priority below 10) or after other plugins (set priority to a large number). It was needed for the update plugin and the feature is available to all.

**Comment by schulle4u** [comment]
OK, finally got it to work, simply by adding the complete HTML output in the same `$output` variable. Maybe a bit ugly. :)

**Comment by markseu** [comment]
Nice workaround. I found an alternative for the JavaScript integration, sent you an email.
