### ISSUE TITLE
Request: step-by-step installation guide for Github.io hosting

### ISSUE THREAD

**Issue by sp-am** [datenstrom/yellow#208]
Hello all, 
Would it be possible for someone to write a step-by-step set of instructions for using Yellow CMS on github.io? I use the mac desktop version of github, specifically. I have the tiniest of websites, and I am tired of spending $60-100 a year just to host it, when all I need is a few mb of space. Github would be excellent if at all possible. 
Thanks!

**Comment by nibreh** [comment]
Hello. I don't think github.io accept PHP files. Correct me if I'm wrong.

In that case, you first must create your content & config files locally, then generate your static website in commandline with php. Finally, upload your static website on github.

How to create your static website with Yellow:
https://developers.datenstrom.se/help/web-server-configuration

Otherwise, you can also take a look at this online editors and CMS to manage your website hosted by github.io:

- https://github.com/cdmedia/cms.js
- https://kissmyblog.com
- https://github.com/mgax/jekyllcms
- https://github.com/prose/prose
- https://github.com/mushishi78/content-editor
- https://github.com/isnowfy/simple
- https://github.com/38911BytesFree/TiddlyWiki

Maybe someone who knows better than me how to host your site on github.io can help you because I don't know very well how it works.
