### ISSUE TITLE
Plugin for intraged of facebooksite - twitter feed

### ISSUE THREAD

**Issue by BogusCurry** [datenstrom/yellow#212]
Hello ;D
I search a Plugin for intraged from facebooksite and twitter-feed ;D

Greetings
Bogus

**Comment by markseu** [comment]
Hi Bogus, 

as far as I know there's no plugin to integrate Facebook and Twitter.

**Comment by BogusCurry** [comment]
Hi ;D
Thanks for the fast answer ;D Hmm .. how difficult is it, a plugin to make for this ? I must say, I am not a coder ;D
Greetings
Bogus

**Comment by markseu** [comment]
I don't know how difficult a plugin for Facebook and Twitter is. You can get started in a weekend. In theory you need to learn about programming, in practice the basic knowledge is quick to pick up. 
Here are some suggestions:

1. [Install the developers kit](https://github.com/datenstrom/yellow-developers). The developers kit includes plugins, themes, examples and documentation. You can try out how to make small web pages, blogs and wikis. It's a great place to get started with the Yellow API.

2. [Learn the web basics](http://www.w3schools.com). Make yourself familiar with HTML, CSS and JavaScript. These are the most important things you need to know to make websites. Yellow requires no complex frameworks and no big libraries.

3. [Put your code on GitHub](https://github.com/datenstrom/yellow/issues?q=label%3Anews%20). Create a repository for each new plugin/theme. The name of your repository should be `yellow-plugin-xyz` or `yellow-theme-xyz`. When your code becomes stable, you can add it to the Yellow main repository.

@nibreh, @richi, @schulle4u  do you have some tips for new developers?

**Comment by nibreh** [comment]
Hi - This websites are in my bookmarks and can help to learn:

http://devdocs.io
https://iwanttolearn.io
http://www.w3schools.com
http://www.phptherightway.com
http://stackoverflow.com

I don't understand what you really want, but here are my answers anyway:

1. If you want to embed any twitter's feed on your website, you can use https://publish.twitter.com. Don't forget, you can sync and connect twitter and facebook in your account's settings.

2. If you want to publish automatically your blog posts from yellow to your twitter account, I think you must create your own application then a plugin for Yellow. Check https://dev.twitter.com & found some scripts/tutorials/help on the web.

3. Otherwise, you can install another CMS like Wordpress, [Known](https://github.com/idno), [Kirby](https://github.com/psedge/kirby-push-to-twitter) etc ... who have already plugins to publish automatically your posts to social network. 

**But remember, Yellow is better :)**

Cheers

**Comment by dieli** [comment]
For sharing to twitter/facebook/etc. take a look at the shariff plugin ([Shariff](https://github.com/schulle4u/yellow-plugin-shariff)).

**Comment by BogusCurry** [comment]
Very thanks for the tips and links ;D
