### ISSUE TITLE
Using yellow in Github pages

### ISSUE THREAD

**Issue by neton-bricio** [datenstrom/yellow#245]
Is possible?

Any tutorial for it?

**Comment by nibreh** [comment]
Hello

Take a look at this issue: https://github.com/datenstrom/yellow/issues/208

You can generate a static site with Yellow (html files instead of PHP files)
https://developers.datenstrom.se/help/web-server-configuration

Don't know how exactly Github Pages works, but I know you can host your html files.

https://help.github.com/categories/github-pages-basics/
https://pages.github.com/

Cheers

**Comment by eli-oat** [comment]
This is a great question. 

Github pages can be used to host static files, and includes automatic compilation for jekyll sites. Yellow is written in PHP, but can also be used locally to generate static files. You can then push those static pages to Github pages without a problem. 

- Create a repo where you'd like to host your site, if necessary create a gh-pages branch (I believe this is necessary for everything other than a repo with your user name)
- Use yellow to generate static assets:

```bash
$ php yellow.php build /path/to/your/cloned/repo
```
- Push those static assets to your gh-pages repo!
