### ISSUE TITLE
Not all Plugins work

### ISSUE THREAD

**Issue by ChristianK89** [datenstrom/yellow#267]
Hello Folks,

Not all Plugins work for me... i am interestet in using markbar and inline file Upload but both are installed and wont show up to use. But some Plugins like twitter Timeline works perfect. Is there an issue ?

**Comment by schulle4u** [comment]
Plugins listed under "experimental plugins" are maintained by 3rd-party developers such as me. You therefore should open an issue in the respective project. 

As it seems the markbar and inline attachment plugins by @nibreh have not been updated to changes in latest webinterface plugin, which is called "edit" since v0.7.1. Fixing them however should be easy. 

Steffen

**Comment by nibreh** [comment]
Hi. 

I will update my plugins for Yellow this summer :)

Thanks for your interest.

**Comment by ChristianK89** [comment]
Thank you.

**Comment by nibreh** [comment]
Hi.

I update [markbar plugin](https://github.com/nibreh/yellow-plugin-markbar) & [Inline Attachment plugin](https://github.com/nibreh/yellow-plugin-inline-attachment). Now working with Yellow 0.7.1.

If you find some bugs, please open an issue in the respective project.

Cheers

**Comment by nibreh** [comment]
Little update: now Inline Attachment plugin use the shortcut `[image filename.jpg]`.

Don't forget that unofficial plugins are experimental 😄 

This issue can be closed.
