### ISSUE TITLE
Numbered page results 

### ISSUE THREAD

**Issue by sri1985** [datenstrom/yellow#325]
Is there any plugin that enables Numbered Results. Currently the results are given as "Next", Previous. If there is a numbered result like: 1 2 3 4 5 ...10 etc,, it would be really great! This is really needed in the Blog page.

Thanks

**Comment by markseu** [comment]
I am sorry, not that I know. How about making your own pagination snippet? Have a look at file `system/themes/snippets/pagination.php` You can use the functions `getPaginationNumber()` and `getPaginationCount()` to create a numbered result. See [API](https://developers.datenstrom.se/help/api) for more information.

**Comment by StephanWeinhold** [comment]
I needed this too, so there you go: https://gist.github.com/StephanWeinhold/8c97efe6862abb7a246ad94dbf4a09fb

**Comment by markseu** [comment]
Thank you Can you elaborate a little bit on the template coding style and what could be improved?

**Comment by StephanWeinhold** [comment]
I prefer a more readable style (line breaks after PHP-tags; curly brackets instead of colons; spaces between statement and parentheses; line break before an `else`; semicolons to mark the end of a line; etc.). **But** I know that maintaining templates is way more complicated then. So I totally understand why you chose this style - pardon my hint! And thanks for asking!

**Comment by StephanWeinhold** [comment]
I'm sitting in a Kanban seminar at this moment - sounds familiar ;)
