### ISSUE TITLE
EDIT - create user account

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#340]
Yellow has a good user verification system, however...

is it best practice to have "create user account" available to the public? / hackers? /spammers
OR
should it be part of the the settings menu?
therefore reducing the amount of exposure to hackers/spammers.

![new](https://user-images.githubusercontent.com/16368709/42195068-3b4460e6-7ecb-11e8-9e6f-c04b8b397cb8.png)

![new2](https://user-images.githubusercontent.com/16368709/42194680-374b6eb4-7ec9-11e8-9b62-f067a26bd1f1.png)
![new3](https://user-images.githubusercontent.com/16368709/42194885-3d22d45c-7eca-11e8-8e16-55a3c266da21.png)

**Comment by markseu** [comment]
I understand that you want to have the features that make you feel safe. 

When designing products it's good to understand what people need, because you want to **make a product useful**. Most users want to create user accounts in the browser, because they prefer no effort over even a little effort. When designing products it's also good to make important features adjustable, because **one size doesn't fit all**. Users can adjust their security configuration, can add as much protection as they need. You can restrict the login if you must, so that nobody can create user accounts. You can also keep the login as it is, let the webmaster approve or decline new user accounts.

Let's keep the login page as it is, perhaps an IP filter can add an additional security layer in the future.

**Comment by nzyeehaa** [comment]
thanks for your response and the link...
I currently hide the link manually - but that `config.ini` user login setting hides it for me... brilliant...
(I had discovered it previously but had forgotten all about it)

With `EditLoginRestrictions: 1` the visible link is hidden through css styling...
the form still remains accessible through HTML, and a new user can still be created...
the user verification process will still be in place.
