### ISSUE TITLE
ShowTimer plugin

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#352]
Since I was annoyed that I always had to (manually) delete holiday announcements immediately from a website  after expiration, I wrote "ShowTimer". This allows you to hide a (markdown) sections after or display a short text up to an appointment.

```

[showtimer 2018-08-01 start]

This text will be marked as HTML comment as of August 2, 2018 
and will then only be visible in the HTML source code.

[showtimer 2018-08-01 end]

[showtimer 2018-12-31 "This text will be completely removed on 1st January 2019"]

```

https://github.com/BsNoSi/yellow-plugin-showtimer

Update: installer added

**Comment by schulle4u** [comment]
Nice idea. But what is the advantage of putting site elements in HTML comments? You are already using php, so you could also completely remove the whole output when the event is over.

**Comment by BsNoSi** [comment]
If you'll be so kind to explain how I can transfer a variable part of the mardown text in a file (headings, lists, …) into a plugin *and* the output is parsed by the markdown plugin I will imediately improve the plugin.

- Is there an option to "shoot out" text with a plugin?
- Is there an option to get the output parsed by the markdown plugin?

I had in mind to make it usable for end users. Therefore, no special coding or *tricky* structure is acceptable. The (currently) found solution is easily to handle for everyone able to write markdown. This was the main intention.

I have to admit that I am a php beginner. All I have done with php as yet can be found in my github repository.

**Comment by BsNoSi** [comment]
I forget to answer shulle4u's question: The advantage is hidden text. A typical site visitor does not check if there is something commented, does he/she?

**Comment by schulle4u** [comment]
Regarding parsing of markdown files: The Yellow API is a mighty little thing. At least you can include whole pages into the current page, see my [global plugin](https://github.com/schulle4u/yellow-plugin-global) for an example. I'm sure it could be modified to optionally include specific parts of a page. However I would have to investigate this first to give you an exact explanation. For now you could use it together with your plugin to have a less cluttered markdown file and put all your event pages in one hidden folder so that you only have some shortcuts in the markdown file responsible for the output. 

And no, most people won't read websites in source mode unless they aren't Borg. :) But when I have a programming language at my hand that allows to cleanly divide content from program logic, I would try to use this as much as possible. Of course it totally is your decision. The main thing is to make it work. Probably my plugins often look like this too.

**Comment by BsNoSi** [comment]
Based on shulle4u's `global` plugin I created [ontime](https://github.com/BsNoSi/yellow-plugin-ontime).

- Offers a `create` link if the given file does not exist
- Writes an ugly warning if you miss a file
- shows external content (similar to `Global` )
- processes start and end date in any combination to show/remove the external content

`Showtimer` therefore is *deprecated*.

Additionally, I created [cmail](https://github.com/BsNoSi/yellow-plugin-cmail).

It creates a formatted e-mail with a backlink. Some more options can be configured directly in the plugin file (I wanted to have it all together instead of adding and editing the config.ini entries).
