### ISSUE TITLE
How to use the new shortcut handler

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#392]
I'm currently updating my plugins for the new shortcut handler function, which seems to have a slightly different syntax. 

```
// Handle page content of shortcut
public function onParseContentShortcut($page, $name, $text, $type) {
    $output = null;
    if ($name=="example" && ($type=="block" || $type=="inline")) {
        ...
    }
}
```

Is there something what technically differs the `block` and `inline` shortcut types? Do you have an example in which cases an `inline` shortcut should be used? 

Thanks
Steffen

**Comment by markseu** [comment]
Here are some technical explanations, why there are multiple types: The Markdown parser checks first if someone wants to handle `block` shortcuts, which means your plugin provides HTML-code for a line of Markdown. Then the Markdown parser check if someone wants to handle `inline` shortcuts, which means your plugin returns a partial HTML-code for a line of Markdown. By the way, there are even more types. For example `code` is used for preformatted code blocks.

In practice your plugin could handle inline shortcuts only. For example the image plugin does this, all Markdown images are inline elements. The generated HTML-code will be surrounded by `<p>...</p>`, inline shortcuts are automatically part of a paragraph (or another parent element). That's why there are block shortcuts, in case people want to have more control over the HTML-code. For example to generate a `<div>...</div>`. See also #374.

As a simple guideline.... handle `block` and `inline` shortcuts, that's what most plugins do. 

Hope this helps. :smile:

**Comment by schulle4u** [comment]
Thank you, thats an explanation I can work with. :)
