### ISSUE TITLE
More themes wanted

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#41]
Hi, the visual design of a website is defined with themes. Colors and so on. It would be good to have a wide range of [ready-made themes](http://developers.datenstrom.se/themes/) to chose from. Feel free to suggest a web design you like. Any help creating themes would be hugely appreciated. :smile: 

Helps us grow this list: https://github.com/datenstrom/yellow-themes

**Comment by nibreh** [comment]
Hi Mark

The old theme _Knowbase_ was a good one (like the famous minimalist theme for indexhibit made for artist // portfolio)

cheers

**Comment by markseu** [comment]
Thanks @nibreh for the idea, added Ariane theme (based on Knowbase theme). :+1:

**Comment by Fourwinged** [comment]
I will be making a few themes in the following months, including a "portfolio" one. I feel Yellow is the CMS I was looking for.
Are there any people who shared with you their Yellow-based websites ? If so, it might be nice to have a showcase somewhere, to show what can be built with it.

**Comment by markseu** [comment]
That's good news. I don't think there's a list of example websites, it could be nice to have.

**Comment by nibreh** [comment]
hello.
I modified snippet imagelist and added justified gallery & fancybox:
[include snippet gallerylist cafescope/.*.jpg]
give me:
http://nibreh.legtux.org/site/cafescope/
if this can be useful for a portfolio theme

http://miromannino.github.io/Justified-Gallery/
http://fancyapps.com/fancybox/

**Comment by nogginfuel** [comment]
When creating a new theme, if I want to use a framework that has multiple CSS and JS files such as [Zurb Foundation](http://foundation.zurb.com/) is the best place to link the files in the **header.php** and **footer.php** files?
Currently the only themes in use are single file CSS and they are called in per page via the, _Template: knowhow_ method at the top of the page file. I'm not sure that will work for a framework since it has/may have multiple files that need called. Thoughts? Suggestions?

**Comment by markseu** [comment]
I don't know about Zurb Foundation, according to their [FAQ](http://foundation.zurb.com/learn/faq.html) it's possible to integrate it with any CMS. What I can say about Yellow is that if you put CSS and JS files into `system/themes` folder they can be accessed via location `/media/themes/`. Here's an example code:

`<link rel="stylesheet" type="text/css" media="all" href="<?php echo $yellow->config->get("serverBase").$yellow->config->get("themeLocation")."example.css" ?>" />`

`<script type="text/javascript" src="<?php echo $yellow->config->get("serverBase").$yellow->config->get("themeLocation")."example.js"></script>`

**Comment by nogginfuel** [comment]
Thanks for the input. I'll start poking at the code in the morning to see if I can start making progress.

**Comment by markseu** [comment]
Making themes just got easier. CSS and JS files will be automatically detected. You can add something like `system/themes/example.css` and `system/themes/example.js` and they will be automatically used.

**Comment by nogginfuel** [comment]
@markseu this is a great update. Hopefully after I get my custom site launched I can circle back and make another theme or two.

**Comment by TUBii** [comment]
@markseu Good idea :+1:

**Comment by markseu** [comment]
**Lördagsgodis bounty**

Here's a bounty for web designers. [Create a Yellow theme](http://developers.datenstrom.se/help/yellow-themes) and receive chocolates from Sweden. Lördagsgodis is a Swedish tradition. It literally means Saturday candy, that's when kids get chocolates and sweets for the weekend. So if you happen to know CSS and like the idea of open source software: 

1. Create a new Yellow theme, upload it to your GithHub account. 
2. Doesn't have to be perfect, just working with the developers kit. 
3. Add a link and [send a pull request](https://github.com/datenstrom/yellow-themes). 

Once you're listed as [contributor](https://github.com/datenstrom/yellow-themes/graphs/contributors), claim your bounty. :chocolate_bar: :cookie: :smile: :stuck_out_tongue:

**Comment by nogginfuel** [comment]
Do I need to create another theme to claim my bounty? I've been meaning to circle back and create another one.

**Comment by markseu** [comment]
No you are good to go @nogginfuel, please send me an email.

**Comment by nibreh** [comment]
Hi

I made a new theme inspired by Indexhibit ([take a look on this website](http://eatock.com/)).

My theme is LATERAL and offers a fixed sidebar.
https://github.com/nibreh/yellow-theme-lateral

![lateral](https://cloud.githubusercontent.com/assets/7314006/13998206/4851977e-f136-11e5-972f-bd4c7c8c0409.png)

Suggestions are welcome to make it better. 

Thanks.

**Comment by TUBii** [comment]
@nibreh Clean stuff :) Perfect for blog!

**Comment by markseu** [comment]
@nibreh Thank you, please send me an email to claim your bounty.

**Comment by nibreh** [comment]
I would like to introduce some free and open source templates. Maybe some people with skills will be interested. Cheers.

http://startbootstrap.com/ - (MIT Lience)
http://templated.co/ - (Creative Commons)
http://html5up.net/ - (Creative Commons)
http://bootswatch.com/ - (MIT Lience)
http://getskeleton.com/ - (MIT Lience)
http://materializecss.com/ - (MIT Lience)
http://purecss.io/ - (Yahoo BSD License - ??)

**Comment by BsNoSi** [comment]
I tried "Lateral" in the developer kit by simply switching to it, because it looks nice. I recognizes two things. First is cosmetic:

![lateral01](https://cloud.githubusercontent.com/assets/2784683/14072638/ac26980a-f4c2-11e5-9ebf-f5258d4c06d3.png)

Second maybe a challenge of "sidebar" behavior, that should collapse for instance into a hamburger menu, otherwise the site may be not accessible on mobile devices:

![lateral02](https://cloud.githubusercontent.com/assets/2784683/14072681/0205cdcc-f4c3-11e5-9058-3f22f4d80c92.png)

I tried with current Opera, Edge, Firefox and Vivaldi. Behavior is same in each.

I am aware that this test may not fair, because developer kit is not optimized for "lateral". But standard themes do not lose menu (blog, flatsite, knowhow). Therefore this should be fixed to make them interchangeable.

**Comment by nibreh** [comment]
Hello @BsNoSi.

About the cosmetic, when you install a plugin like blog or wiki, you must make some changes in your snippets and templates to adapt them for Lateral. Take a look in the [README.md](https://github.com/nibreh/yellow-theme-lateral/blob/master/README.md), there is an example of HTML structure for Lateral.

I can write a detailed example on how to do it, or simply upload the correct snippets and templates for blog and wiki. What do you think ?

For the mobile device, I did not try to do better. because my skills are limited ;)

Currently, when windows browser is reduced (mediaqueries), it works this way: the sidebar is hidden (`<div class="content sidebar">`) and the classical menu (in fact, the `<div class="header">`) is displayed. 

I agree, It's not pretty ! I will look for some script to make a hamburger menu.

Don't hesitate to write issues in my repository.

Cheers

**Comment by nibreh** [comment]
Here it is ! 

### The new [Lateral 0.2](https://github.com/nibreh/yellow-theme-lateral)

**Now Lateral work with the default website/blog/wiki out of the box**
(_no more snippets or template to upload/adapt_)

**Now sidebar is displayed at the top on mobile device**
(_just add your favorite script for hamburger menu_)

![lateral-screenshot](https://cloud.githubusercontent.com/assets/7314006/14095032/21c14472-f55c-11e5-94ef-270df19adc82.png)

I was wrong in my first attempt ;)

Thanks @BsNoSi & @markseu for your advice

**Comment by hysonlee** [comment]
Good job, want to have a try!
________________________________
发件人: nibreh<mailto:notifications@github.com>
发送时间: ‎2016/‎3/‎29 9:20
收件人: datenstrom/yellow<mailto:yellow@noreply.github.com>
主题: Re: [datenstrom/yellow] More themes wanted (#41)

Here it is !

### The new [Lateral 0.2](https://github.com/nibreh/yellow-theme-lateral)

**Now Lateral work with the default website/blog/wiki out of the box**
(_no more snippets or template to upload/adapt_)

**Now sidebar is displayed at the top on mobile device**
(_just add your favorite script for hamburger menu_)

![lateral-screenshot](https://cloud.githubusercontent.com/assets/7314006/14095032/21c14472-f55c-11e5-94ef-270df19adc82.png)

I was wrong in my first attempt ;)

Thanks @BsNoSi & @markseu for your advice

---

**Comment by BsNoSi** [comment]
Hi!

I have to admit, that I did not read the readme and did not
remember the #102. I have currently not much time for trying
things with Yellow.  I think the part "how to use a central
sidebar" inside readme should be enough.

Thanks for updating — I will try this again (as soon there is
spare time for testing).

Norbert

**Comment by markseu** [comment]
Thanks everyone for your help. Feel free to open a new issue, if someone wants to work on themes.

Have a good weekend.
