### ISSUE TITLE
Missing translations? → Clean up INI files!

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#428]
After upgrading from an older installation of YELLOW to 0.8.4 some of the translations got lost. 

I found the solution in cleaning up my system.ini that contained old settings. Comparing it with another (working as expected) system.ini I found "ResourcesDir" set to "media/resources/" in the not working configuration set. Have no idea how this happened but changing it to "system/resources/" and removing the obsolete settings everything worked fine (again).

This is not an issue, this is a "todo" after upgrades from older installations. ;)

**Comment by schulle4u** [comment]
Actually you don't have to do this manually since the update process takes care of old settings and removes/comments them. Depending on how old your installation is, you will need to re-run the update check after the first attempt. This should fix translation and other ressource issues. If the problem persists, press CTRL+F5 to force your browser to refresh the site without using a cached version. I had this problem too, and these steps solved it perfectly. 

Steffen
