### ISSUE TITLE
How display all tags?

### ISSUE THREAD

**Issue by sashatravkina** [datenstrom/yellow#444]
Hello. How I can show all tags from blog posts on my homepage?

**Comment by schulle4u** [comment]
Simply enter `0` for the `PagesMax` parameter in your `[blogtags]` shortcut, e. g. `[blogtags /blog/ 0]`.

**Comment by sashatravkina** [comment]
How I can show it with html/php on my layout/home.html?

**Comment by markseu** [comment]
With the API you have access to all pages. It's a little bit more work to show tags, since each page can have multiple tags, which means you probably want to split page meta data into individual tags. I checked the API documentation, looks like there's no example you can simply copy/paste. 

As a starting point, see function `getShorcutBlogtags()` in file `blog.php` of the blog extension.
