### ISSUE TITLE
Custom fields in Edit extensions

### ISSUE THREAD

**Issue by khomutovspace** [datenstrom/yellow#484]
I want to offer an idea for an Edit extension. Now it is ok to set variables via adding some string in to the Markdown file header. But I think there can be more easy way. My idea is to add a feature, which can allow developer set fields for string, and user (admin or editor) just fill them as a usual text field or a file picker field. It would be much easier for client to work with.

**Comment by schulle4u** [comment]
Hmm, wouldn't this make things more complicated in the end, for both users and developers? The only solution I can imagine is to parse all `setting: value` pairs from a markdown header and display them as form fields in the editor. However this actually isn't worth the effort as we cannot determine the field type and will use simple text input fields for each value. In my opinion this wouldn't increase the usability that much. But let's hear the crowd. 😀

**Comment by BsNoSi** [comment]
I can not see an advantage or need of this. I have modified my default pages (shared folder) which can hold all required / wanted options and I delete the unwanted ones (sample taken from my German blog with some comments to explain):
```
---
title: 
?TitleSlug: (for instance, if there are German umlauts in title to avoid them in filenames
?TitleContent: if a different title is convenient
?TitleNavigation: if page title is to long for navigation
?TitleHeader: Title in tab of browser
? Help: https://github.com/datenstrom/yellow-extensions/blob/master/features/core/README-de.md#einstellungen-status
description: 
tag: Abseitig,DSGVO,Gedanken,Gesellschaft,Medien,Meinungsfreiheit,NoSi.de,Politik,Recht,Technik
keywords: 
Layout: blog
published: @date
modified: @date  
author: @username
language: de 
Sidebar: sidebar
Image:    ?@timestamp
ImageAlt: 
Status: draft unlisted public
---
```
Lines starting with `?` in most cases are deleted – they are reminders saving the time of looking it up in documentation – therefore the link to it, if something very special is required. Removing the `?` *activates* the entry, if forgotten to delete they are ignored (I delete them to keep header information clean).

Tag line contains the list of tags I decided to limit them to. This ist the complete set where I can pick the desired ones by deleting the unsuitable.

Image: …`?@timestamp` is a prepared numeric successor to force twitter for retry if image fetching failed first time. The other `@`-entries are replaced by the named system data.

Because I typically prepare my files in an external editor it would be quite useless for me to have fields that can be filled after inserting my text to the editor. This would be in my personal opinion somehow contradictious to the concept of the simplicity of markdown.

**Comment by i-do** [comment]
@BsNoSi, trying to solve the same case: I want to make a theme with custom fields so I need add the html code to editor button. 

Will be very grateful for some advice or manual how can I make it.

**Comment by BsNoSi** [comment]
If you're talking about the editor for content this is not possible by modifying the theme. The editor is a general plugin.

I created a small plugin for this challenge: [format](https://github.com/BsNoSi/yellow-extension-format).

Should work with current version – if not, please, let me know (if you try to solve your challenge with it).

Usage would be

```
[format marginnote]
  The Margin Text
[format /]
```

creates

```

<div class="marginnote">
The Margin Text
</div>
```

**Comment by i-do** [comment]
[Simon](@BsNoSi), that's was very quick! 
Will try it soon, thanks a lot!

**Comment by datenstromse** [comment]
Thanks for your feedback. I am afraid to say that we don't support this, not unless there is more demand. We can't promise if we may add something like this later. However we definitely appreciate the feedback. If you want to make a new extension, [go ahead and let us know if you need help](https://datenstrom.se/yellow/help/contributing-guidelines).
