### ISSUE TITLE
Datenstrom developers meeting

### ISSUE THREAD

**Issue by datenstromse** [datenstrom/yellow#509]
We would like to host an online developer meeting to discuss latest changes, roadmap, questions about Datenstrom Yellow and get to know each other. Reply if you’re interested and please tell which date/time would be good for you, we suggest Friday evening at 21:00 CEST (7 PM UTC), either April 24th or May 1st.

Stay safe and kind regards from Sweden.

**Comment by BsNoSi** [comment]
I am still a php-beginner and can only deal with Yellow sporadically.  But I like the idea. 

Why so late at night? Because my day starts very early, my concentration is quite bad at this time of the day. Regardless to this personal "handicap" I could do both dates. 

Which technique is proposed? I would use Zoom only very reluctantly.

**Comment by schulle4u** [comment]
So far we have successfully tested the [TeamTalk voice conferencing system](https://bearware.dk). It is similar to TeamSpeak, but without unnecessary features. We can run our own server, and clients are freely available for all mobile and desktop platforms. I personally don't have much experience with browser-based solutions like Jitsi Meet.

**Comment by BsNoSi** [comment]
For a proper preparation of this meeting it is about time for
- a binding date
- an Agenda
- a timeframe
- targets

**Comment by datenstromse** [comment]
Ok, let's do this on Friday evening, May 1st at 21:00 CEST (7 PM UTC).

**Comment by BsNoSi** [comment]
Since I don't have any more concrete data yet except a date for the meeting, it was either planned for a closed circle (why then published here?) or the idea was discarded in the meantime. I came to this conclusion because I don't have any other information except date and time - too bad. 

I have now planned the evening with my wife. I would have liked to take the time for a meeting, but due to sufficiently frequent negative experiences, I don't spent time anymore on meetings whose  framework, number of participants and technology is still completely unclear a few hours before the beginning. 

Until all this is cleared up, everyone is usually so annoyed that no relevant result is achieved anyway and many people don't give a second aptempt a try, no matter how perfectly prepared it might be. I don't want to be part of such an event anymore. 

If there should be a better planned one or the need for an organizer for a solidly prepared event, I am very open for it.

**Comment by GiovanniSalmeri** [comment]
I am really sorry for not answering earlier, I forgot the calendary and it slipped my mind! Unfortunately my contributions of the latest days are not the sign of more spare time, but the (fortunate :-) by-product of something very urgent on which I am currently working and which I have to complete as soon as possible. If another meeting is scheduled I will gladly take part. Perhaps it could be prepared in this same thread? As soon as possible I would be glad to write down and share my experience, the experience of other people who use Yellow, and my little future projects.

**Comment by hysonlee** [comment]
Although I was unable to participate in this real-time developer meeting due to limited and various conditions, I will still pay attention to the development of Yellow when I have time.Hope all is well.

**Comment by datenstromse** [comment]
We're online soon. If you like to join, the connection details can be found at:
https://datenstrom.se/yellow/help/

**Comment by datenstromse** [comment]
Next meeting Monday evening, June 1st at 21:00 CEST (7 PM UTC).
Planned is a question and answer session, via voice and text chat.

**Comment by datenstromse** [comment]
Next meeting Monday evening, June 1st at 21:00 CEST (19:00 UTC).
Planned is a question and answer session, via voice and text chat.

**Comment by BsNoSi** [comment]
Is an address available where I can sign up for the meeting and get the required information for technical prerequisite, login data, …., in return?

Perfectly there is a "dummy conference room" to test if my setup works fine and does not interfere to or with anything.

**Comment by markseu** [comment]
I have tested [Jitsi Meet](https://meet.jit.si) and suggest to use it for next meeting. It's simple and works in any modern web browser. We probably have to run our own server, unfortunately the public server is without sufficient control and safety (https://github.com/jitsi/jitsi-meet/issues/5407 + https://github.com/jitsi/jitsi-meet/issues/5653).

**Comment by BsNoSi** [comment]
You made my day – just now I was thinking about the name of the very well working service I have tested with my brother a view weeks ago…

We tested [https://meet.golem.de/](https://meet.golem.de/) → see [article](https://www.golem.de/news/homeoffice-videokonferenzen-auf-eigenen-servern-mit-jitsi-meet-2003-147239.html).

The security risk can be reduced tremendously by choosing a accidental room name sent by mail to Participants. 

Do not know the effort of a Jitsi setup and – maybe – it is worth thinking about how secure an open discussion about an open software has to be in compare to the effort to achieve something that will end up in ideas noted here publicly…

**Comment by markseu** [comment]
We have tested [TeamVideo conferencing system](https://team.video/datendesigner). It is similar to Jitsi Meet, but with a nicer user interface and better web browser support. The public server is free to use, so it could be an alternative for our next meeting.

**Comment by BsNoSi** [comment]
- Free version (→ limited to seven participants and 60 minutes) or…?
- Leads the link to a specific room (that would be now public without access control) ?

The tool does not matter. It should be free or of low price and offer a basic security to participants.
To achieve this "basic security" I think that you should invite participants by message with access information that you have control over the conference.

**Comment by BsNoSi** [comment]
Because the categorical "no" to configurable white/blacklisting I took a look over the fences I have built myself around Yellow as "all purpose tool".  I compared against popular/successful flat file systems and as far as I could explore in short they all have configurable options to control filtering.

With this "no" Yellow looses for me much of it's attraction because it leads to much higher outlays to achieve the results I had up to now.  Against the examined competitors Yellow has still unbeatable advantages but to categorical restrictions I have a tense relationship. Other projects in the past where this took place, typically went insignificant or disappeared completely.

The currently most important aspect for me was taken off the discussion list with this "no". I have to reconsider future and existing projects with Yellow from the named points of view at the moment.  I am sorry to say that but on this basis it doesn't make sense for me to attend the developer meeting.
