### ISSUE TITLE
navigation menu

### ISSUE THREAD

**Issue by stratego72** [datenstrom/yellow#535]
Hello,

I've add file in the &-home directory but the menu bar don't have changed

Any Idea ?

Thx

**Comment by stratego72** [comment]
thanks for the support

**Comment by JetGum** [comment]
Hello stratego72,

did you create sub-menus? Or just added level-1 content? More info is always appreciated. Screenshots, code snippets, settings, whatever helps to understand your problem.

If you have figured out in the meantime you can let us know how you did it and what the problem was.

Cheers,

Carsten

**Comment by datenstromse** [comment]
I am closing this as idle. Thank Carsten for your answer, your help is much appreciated.
