### ISSUE TITLE
Snippets Explanation

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#75]
How can I use snippets? Yes, I've read manual. 
Snippets is the separated code parts, am I right?

Where is snippet call must be placed — inside theme in [template] (https://github.com/datenstrom/yellow/wiki/Yellow-customisation)? 

    How to make a list?
    -------------------
    Add a snippet in the format `$yellow->snippet("pagelist")`

Can you help with example for pagelist?

**Comment by markseu** [comment]
Snippets are called from templates or snippets. 

You can call the old pagelist snippet from file  `system/theme/snippets/content-main.php`:
```
<div class="content main">
<h1><?php echo $yellow->page->getHtml("titleContent") ?></h1>
<?php echo $yellow->page->getContent() ?>
<?php $yellow->snippet("pagelist") ?>
</div>
```

If you like you can also use the [preview plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/preview), it does pretty much the same as the snippet above. Instead of adding a snippet you add a shortcut like` [preview /themes/]` to your page. Many people find it easier to use shortcuts than snippets, that's why I moved functionality into plugins.

Hope this helps. Happy coding! :smile:

**Comment by i-do** [comment]
Thanks, Yellow rocks!
