### ISSUE TITLE
feed.php displays modified pages.txt

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#94]
I am using the feed plugin for generating an xml stream, to include it in another page. This works fine.

**A view perceptions**

- blog pages are cut off, if I place a `[--more--]` label in the text. (perfect)
- static pages are displayed as well, but `[--more--]` is ignored (better: should be possible to shorten them, too)
- placeholder pages  without further content (i.e. page.txt) are shown as empty page in feed (with *generator* notice as text), if they are recently modified. This is basically correct, but looks irritating in feed page.

**Workaround**

To hide to long static pages or recently modified generated pages, I placed  `modified:2010-01-01` in the header. This works fine to hide any unwanted files in stream.

**Maybe better**

- Extending feed-plugin with an option to select a single folder for it (or a set of folders). This would be useful, to offer i.e. a single "blog" stream.
- `[--more--]` should be recognized in static files, too.
- Template-files should carry a `modified:1970-01-01` with a short explanation, describing the reason/need for it.

**Comment by markseu** [comment]
You can make a blog feed by replacing `$pages = $this->yellow->pages->index(false, false);` with `pages = $this->yellow->pages->index(false, false)->filter("template", "blog");`. Please note that there are two occurrences in the original feed plugin.

In order to show only the part before a page break `[--more--]` you modify the following line as well:
`$description = $this->yellow->toolbox->createTextDescription($page->getContent(), 400, false, "<!--more-->");`

Hope this is what you are looking for. As a developer you can customise and adjust your website in many ways. Check out the [Yellow API](https://github.com/datenstrom/yellow/wiki/Yellow-API) for more information and ask if there are more questions. :smile:

**Comment by markseu** [comment]
I updated the feed plugin with the second modification, now XML files show only the part before a page break. Thanks for the suggestion, Norbert!
